### PR TITLE
fix consonant clusters

### PR DESCRIPTION
**Pull request by FredericBlum**
I have added some fixes which address #50 .

- [x] Move unused files in /etc/ to etc/archive/
- [x] Add some fixes to pre-nasalized stops
- [x]  Add some fixes for y/j

I tried to keep the impact as minimal as possible, by adding as much phonological context as possible. I have also focused on the clusters that seemed most drastic (C>4). With the added changes, I think we could start the release. But it would be great if you could double-check on the changes and their implications @tihomirrangelov . I have also tagged @SimonGreenhill and @antipodite to have more eyes.

### CODE REVIEW

**Review by tihomirrangelov — APPROVED** [review]
Looks all good to me.

**Comment by SimonGreenhill** [comment]
Awesome, thanks for your help with this @tihomirrangelov !

**Comment by SimonGreenhill** [comment]
@FredericBlum -- can you add Timo's changes to the main abvd lexibank https://github.com/lexibank/abvd dataset too please? the languages are the same (as for the abvd_philippines)

**Comment by FredericBlum** [comment]
The CLTS-mapping over there seems to work differently, since there is no orthography profile file. So I don't think adding the changes is possible. I'll have to leave that to the ABVD team I guess.

**Pull request merged**
