### PR TITLE
Update data to match the ABVD

### PR DESCRIPTION
**Pull request by SimonGreenhill**
This updates the data to be after Mary's latest revision of the dataset.

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
(@maryewal -- mainly tagging you in here so you know that I've added Nukumanu into the dataset)

**Comment by maryewal** [comment]
Thanks, @SimonGreenhill. Did you also want to update the glottocodes in this set? I can send those quickly if so...

**Comment by SimonGreenhill** [comment]
Hmm, they should all be updated -- can you send?

**Comment by maryewal** [comment]
> Hmm, they should all be updated -- can you send?

Added ones that need to be changed to code:
[https://github.com/lexibank/abvdoceanic/blob/main/changed_glottocodes](url)

**Comment by SimonGreenhill** [comment]
fixed now.

**Review by maryewal — APPROVED** [review]
Reviewed.

**Review by antipodite — APPROVED** [review]
Looks good oi

**Pull request merged**
